package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Games generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "games")
public class Game implements Serializable {

  @Id
  private Integer id;
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "home_team_id")
  private Team homeTeam;
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "away_team_id")
  private Team awayTeam;
  private Date newDate;
  @Column(name = "home_score")
  private Integer homeScore;
  @Column(name = "away_score")
  private Integer awayScore;
  private byte playoff;
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "game")
  private Set<Scorer> scorers = new HashSet<Scorer>(0);

  public Integer getId() {
    return this.id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public Team getHomeTeam() {
    return this.homeTeam;
  }

  public void setHomeTeam(final Team homeTeam) {
    this.homeTeam = homeTeam;
  }

  public Team getAwayTeam() {
    return this.awayTeam;
  }

  public void setTeamsByAwayTeam(final Team awayTeam) {
    this.awayTeam = awayTeam;
  }

  public Date getNewDate() {
    return this.newDate;
  }

  public void setNewDate(final Date newDate) {
    this.newDate = newDate;
  }

  public Integer getHomeScore() {
    return this.homeScore;
  }

  public void setHomeScore(final Integer homeScore) {
    this.homeScore = homeScore;
  }

  public Integer getAwayScore() {
    return this.awayScore;
  }

  public void setAwayScore(final Integer awayScore) {
    this.awayScore = awayScore;
  }

  public byte getPlayoff() {
    return this.playoff;
  }

  public void setPlayoff(final byte playoff) {
    this.playoff = playoff;
  }

  public Set<Scorer> getScorers() {
    return this.scorers;
  }

  public void setScorers(final Set<Scorer> scorers) {
    this.scorers = scorers;
  }

}
