package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Games generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "games")
public class Game implements Serializable {

  private static SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yy hh:mm");

  @Id
  private Integer id;
  @JsonIgnore
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "season_id")
  private Season season;
  @Column(name = "home_team_id")
  private Integer homeTeamId;
  @Column(name = "away_team_id")
  private Integer awayTeamId;
  @JsonIgnore
  private Date date;
  @Column(name = "home_score")
  private Integer homeScore;
  @Column(name = "away_score")
  private Integer awayScore;
  private Boolean playoff;
  @OneToMany(fetch = FetchType.EAGER, mappedBy = "game")
  private final Set<Goal> goals = new HashSet<Goal>(0);

  public Integer getId() {
    return id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public Season getSeason() {
    return season;
  }

  public void setSeason(final Season season) {
    this.season = season;
  }

  public Integer getHomeTeamId() {
    return homeTeamId;
  }

  public void setHomeTeamId(final Integer homeTeamId) {
    this.homeTeamId = homeTeamId;
  }

  public Integer getAwayTeamId() {
    return awayTeamId;
  }

  public void setAwayTeamId(final Integer awayTeamId) {
    this.awayTeamId = awayTeamId;
  }

  public Date getDate() {
    return date;
  }

  public void setDate(final Date date) {
    this.date = date;
  }

  public Integer getHomeScore() {
    return homeScore;
  }

  public void setHomeScore(final Integer homeScore) {
    this.homeScore = homeScore;
  }

  public Integer getAwayScore() {
    return awayScore;
  }

  public void setAwayScore(final Integer awayScore) {
    this.awayScore = awayScore;
  }

  public Boolean getPlayoff() {
    return playoff;
  }

  public void setPlayoff(final Boolean playoff) {
    this.playoff = playoff;
  }

  public Set<Goal> getGoals() {
    return goals;
  }

  public String getPlayed() {
    return sdf.format(getDate());
  }

}
