package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Games generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "games")
public class Game implements Serializable {

	@Id
	private Integer id;
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "season_id")
	private Season season;
	@Column(name = "home_team_id")
	private Integer homeTeamID;
	@Column(name = "away_team_id")
	private Integer awayTeamID;
	private Date date;
	@Column(name = "home_score")
	private Integer homeScore;
	@Column(name = "away_score")
	private Integer awayScore;
	private byte playoff;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gameID")
	private Set<Goal> goals = new HashSet<Goal>(0);

	public Integer getId() {
		return this.id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public Season getSeason() {
		return season;
	}

	public void setSeason(final Season season) {
		this.season = season;
	}

	public Integer getHomeTeamID() {
		return homeTeamID;
	}

	public void setHomeTeamID(Integer homeTeamID) {
		this.homeTeamID = homeTeamID;
	}

	public Integer getHomeScore() {
		return this.homeScore;
	}

	public void setHomeScore(final Integer homeScore) {
		this.homeScore = homeScore;
	}

	public Integer getAwayScore() {
		return this.awayScore;
	}

	public void setAwayScore(final Integer awayScore) {
		this.awayScore = awayScore;
	}

	public byte getPlayoff() {
		return this.playoff;
	}

	public void setPlayoff(final byte playoff) {
		this.playoff = playoff;
	}

	public Set<Goal> getGoals() {
		return this.goals;
	}

	public void setGoals(final Set<Goal> goals) {
		this.goals = goals;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
