package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Scorers generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "goals")
public class Goal implements Serializable {

	@Id
	private Integer id;
	@JsonIgnore
	@OneToOne
	@JoinColumn(name = "game_id")
	private Game game;
	@Column(name = "player_id")
	private Integer playerId;

	@Transient
	private Integer gameId;


	public Integer getId() {
		return id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public Integer getGameId() {
		return this.game.getId();
	}

	public Integer getPlayerId() {
		return playerId;
	}

	public void setPlayerId(final Integer playerId) {
		this.playerId = playerId;
	}

	public Game getGame() {
		return game;
	}

	public void setGame(Game game) {
		this.game = game;
	}
}
