package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Scorers generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "goals")
public class Goal implements Serializable {

  @Id
  private Integer id;
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "game_id", insertable = false, updatable = false)
  private Game game;
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "player_id", insertable = false, updatable = false)
  private Player player;

  public Integer getId() {
    return this.id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public Game getGame() {
    return this.game;
  }

  public void setGame(final Game game) {
    this.game = game;
  }

  public Player getPlayer() {
    return this.player;
  }

  public void setPlayer(final Player player) {
    this.player = player;
  }

}
