package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScorersId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ScorerId implements Serializable {

  @Column(name = "game_id")
  private int gameId;
  @Column(name = "player_id")
  private int playerId;

  public int getGameId() {
    return this.gameId;
  }

  public void setGameId(final int gameId) {
    this.gameId = gameId;
  }

  public int getPlayerId() {
    return this.playerId;
  }

  public void setPlayerId(final int playerId) {
    this.playerId = playerId;
  }
}
