package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.persistence.*;

/**
 * Seasons generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "seasons")
public class Season implements Serializable {

	@Id
	private Integer id;
	private String name;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "season")
	@MapKeyColumn(name="id")
	private Map<Integer,Team> teams = new HashMap<Integer,Team>();
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "season")
	private Set<Game> games = new HashSet<Game>(0);

	public Integer getId() {
		return this.id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	public Map<Integer, Team> getTeams() {
		return teams;
	}

	public void setTeams(Map<Integer, Team> teams) {
		this.teams = teams;
	}

	public Set<Game> getGames() {
		return games;
	}

	public void setGames(final Set<Game> games) {
		this.games = games;
	}
}
