package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * TeamPlayer generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "team_player")
public class TeamPlayer implements Serializable {

	@JsonIgnore
	@Id
	private Integer id;
	@Column(name = "team_id")
	private Integer teamId;
	@Column(name = "player_id")
	private int playerId;
	private Boolean isGoalie;
	private Boolean isCaptain;
	private Boolean isCoCaptain;

	public Integer getId() {
		return id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public Integer getTeamId() {
		return teamId;
	}

	public void setTeamId(final Integer teamId) {
		this.teamId = teamId;
	}

	public int getPlayerId() {
		return playerId;
	}

	public void setPlayerId(final int playerId) {
		this.playerId = playerId;
	}

	public Boolean getIsGoalie() {
		return isGoalie;
	}

	public void setIsGoalie(final Boolean isGoalie) {
		this.isGoalie = isGoalie;
	}

	public Boolean getIsCaptain() {
		return isCaptain;
	}

	public void setIsCaptain(final Boolean isCaptain) {
		this.isCaptain = isCaptain;
	}

	public Boolean getIsCoCaptain() {
		return isCoCaptain;
	}

	public void setIsCoCaptain(final Boolean isCoCaptain) {
		this.isCoCaptain = isCoCaptain;
	}

}
