package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeamPlayerId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class TeamPlayerId implements Serializable {

  @Column(name = "team_id")
  private int teamId;
  @Column(name = "player_id")
  private int playerId;

  public TeamPlayerId() {
  }

  public TeamPlayerId(final int teamId, final int playerId) {
    this.teamId = teamId;
    this.playerId = playerId;
  }

  public int getTeamId() {
    return this.teamId;
  }

  public void setTeamId(final int teamId) {
    this.teamId = teamId;
  }

  public int getPlayerId() {
    return this.playerId;
  }

  public void setPlayerId(final int playerId) {
    this.playerId = playerId;
  }

}
