package com.sas.comp.models;

// Generated Mar 30, 2013 1:36:42 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * TeamPlayer generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity(name = "team_player")
public class TeamPlayer implements Serializable {

	@JsonIgnore
	@Id
	private Integer id;
	@JsonIgnore
	@ManyToOne
	private Team team;
	@Column(name = "player_id")
	private int playerId;
	private Boolean isGoalie;
	private Boolean isCaptain;
	private Boolean isCoCaptain;

	@Transient
	private Integer teamId;
	@Transient
	private Integer shutouts = 0;
	@Transient
	private Integer goals = 0;

	public Integer getId() {
		return id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public Integer getTeamId() {
		return this.team.getId();
	}

	public int getPlayerId() {
		return playerId;
	}

	public void setPlayerId(final int playerId) {
		this.playerId = playerId;
	}

	public Boolean getIsGoalie() {
		return isGoalie;
	}

	public void setIsGoalie(final Boolean isGoalie) {
		this.isGoalie = isGoalie;
	}

	public Boolean getIsCaptain() {
		return isCaptain;
	}

	public void setIsCaptain(final Boolean isCaptain) {
		this.isCaptain = isCaptain;
	}

	public Boolean getIsCoCaptain() {
		return isCoCaptain;
	}

	public void setIsCoCaptain(final Boolean isCoCaptain) {
		this.isCoCaptain = isCoCaptain;
	}

	public Boolean getGoalie() {
		return isGoalie;
	}

	public void setGoalie(final Boolean goalie) {
		isGoalie = goalie;
	}

	public Boolean getCaptain() {
		return isCaptain;
	}

	public void setCaptain(final Boolean captain) {
		isCaptain = captain;
	}

	public Boolean getCoCaptain() {
		return isCoCaptain;
	}

	public void setCoCaptain(final Boolean coCaptain) {
		isCoCaptain = coCaptain;
	}

	public Integer getShutouts() {
		return shutouts;
	}

	public void setShutouts(final Integer shutouts) {
		this.shutouts = shutouts;
	}

	public Integer getGoals() {
		return goals;
	}

	public void setGoals(final Integer goals) {
		this.goals = goals;
	}

	public Team getTeam() {
		return team;
	}

	public void setTeam(final Team team) {
		this.team = team;
	}
}
